# fly.toml app configuration file generated for online-store on 2023-06-14T14:32:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "online-store"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
